#!/bin/bash
# ==============================================================================
# Fail2ban Manager (Production Final Version 2026 - New System, Overwrite-Friendly)
# ==============================================================================

set -e
set -o pipefail

RED="\033[31m"; GREEN="\033[32m"; YELLOW="\033[33m"; BLUE="\033[34m"; RESET="\033[0m"
info(){ echo -e "${BLUE}[INFO]${RESET} $1"; }
ok(){ echo -e "${GREEN}[OK]${RESET} $1"; }
warn(){ echo -e "${YELLOW}[WARN]${RESET} $1"; }
error(){ echo -e "${RED}[ERROR]${RESET} $1"; exit 1; }

check_root(){ [ "$(id -u)" -eq 0 ] || error "请使用 root 权限运行"; }

check_system(){
    . /etc/os-release
    case "$ID" in debian|ubuntu) ok "系统: $PRETTY_NAME" ;; *) error "仅支持 Debian / Ubuntu" ;; esac
}

check_installed(){ dpkg -s fail2ban >/dev/null 2>&1; }

detect_ssh(){
    command -v sshd >/dev/null || error "未找到 sshd"
    SSH_PORT=$(sshd -T 2>/dev/null | awk '/^port /{print $2}' | head -1)
    [ -z "$SSH_PORT" ] && SSH_PORT=22
    if systemctl list-unit-files | grep -q "^ssh.service"; then SSH_SERVICE="ssh"
    elif systemctl list-unit-files | grep -q "^sshd.service"; then SSH_SERVICE="sshd"
    else SSH_SERVICE="ssh"; fi
    ok "SSH服务: $SSH_SERVICE"
    ok "SSH端口: $SSH_PORT"
}

install_packages(){
    info "安装 Fail2ban"
    apt-get update
    apt-get install -y fail2ban python3-systemd
    ok "Fail2ban 安装完成"
}

detect_firewall(){
    if [ -f /etc/fail2ban/action.d/nftables-multiport.conf ]; then
        BANACTION="nftables-multiport"
    elif [ -f /etc/fail2ban/action.d/iptables-multiport.conf ]; then
        BANACTION="iptables-multiport"
    else
        warn "未找到 nftables/iptables action，使用 fallback"
        BANACTION="iptables-multiport"
    fi
    ok "Ban Action: $BANACTION"
}

configure_journal(){
    mkdir -p /etc/systemd/journald.conf.d
    cat >/etc/systemd/journald.conf.d/99-log-limit.conf <<EOF
[Journal]
SystemMaxUse=1G
SystemMaxFileSize=50M
MaxRetentionSec=180day
Compress=yes
EOF
    systemctl restart systemd-journald
    journalctl --vacuum-time=180d
    journalctl --vacuum-size=1G
    ok "系统日志限制完成"
}

configure_ssh(){
    mkdir -p /etc/ssh/sshd_config.d
    cat > /etc/ssh/sshd_config.d/99-security-hardening.conf <<EOF
# Generated by Fail2ban Manager
MaxAuthTries 3
LoginGraceTime 30
MaxSessions 5
MaxStartups 10:30:60
ClientAliveInterval 300
ClientAliveCountMax 2
LogLevel INFO
EOF
    sshd -t || error "SSH配置错误"
    systemctl reload "$SSH_SERVICE"
    ok "SSH加固完成"
}

configure_fail2ban(){
    mkdir -p /etc/fail2ban/jail.d
    chmod 750 /etc/fail2ban /etc/fail2ban/jail.d || true
    cat > /etc/fail2ban/jail.d/sshd-production.local <<EOF
[DEFAULT]
backend = systemd
logtarget = SYSLOG
banaction = $BANACTION
ignoreip = 127.0.0.1/8 ::1
findtime = 10m
bantime = 48h
dbpurgeage = 7d

[sshd]
enabled = true
port = $SSH_PORT
mode = aggressive
maxretry = 3
journalmatch = _SYSTEMD_UNIT=${SSH_SERVICE}.service

[recidive]
enabled = true
backend = systemd
journalmatch = _SYSTEMD_UNIT=fail2ban.service
findtime = 7d
maxretry = 5
bantime = 30d
EOF
    chmod 640 /etc/fail2ban/jail.d/sshd-production.local
    ok "Fail2ban配置完成"
}

test_fail2ban(){ fail2ban-client -t && ok "配置检测通过"; }

start_fail2ban(){
    systemctl enable fail2ban
    systemctl restart fail2ban
    sleep 2
    systemctl is-active --quiet fail2ban || { journalctl -u fail2ban -n 50 --no-pager; error "Fail2ban启动失败"; }
    ok "Fail2ban运行正常"
}

check_fail2ban_running(){
    systemctl is-active --quiet fail2ban || error "Fail2ban 未运行"
    fail2ban-client status sshd >/dev/null 2>&1 || error "sshd jail 未启用"
}

reload_fail2ban(){
    fail2ban-client -t || error "Fail2ban 配置检测失败"
    fail2ban-client reload
    ok "Fail2ban 配置已重载"
}

install_fail2ban(){
    check_system
    detect_ssh
    echo "=============================="
    echo " Fail2ban 安装确认"
    echo "=============================="
    echo "SSH服务 : $SSH_SERVICE"
    echo "SSH端口 : $SSH_PORT"
    echo "封禁时间 : 48h"
    echo "最大失败 : 3次"
    echo "=============================="
    read -p "继续安装? (y/N): " c
    [[ "$c" != "y" && "$c" != "Y" ]] && exit 0

    if ! check_installed; then
        install_packages
    else
        warn "Fail2ban 已安装，将覆盖配置"
    fi

    detect_firewall
    configure_journal
    configure_ssh
    configure_fail2ban
    test_fail2ban
    start_fail2ban
    ok "Fail2ban安装完成"
}

uninstall_fail2ban(){
    detect_ssh
    read -p "确认卸载 Fail2ban? 输入 yes: " c
    [[ "$c" != "yes" ]] && exit 0

    systemctl stop fail2ban || true
    systemctl disable fail2ban || true
    apt-get remove --purge -y fail2ban || true
    rm -rf /etc/fail2ban /run/fail2ban /var/log/fail2ban.log

    if [ -d /etc/ssh/sshd_config.d ]; then
        rm -f /etc/ssh/sshd_config.d/99-security-hardening.conf
        sshd -t && systemctl reload "$SSH_SERVICE" || true
    else
        warn "/etc/ssh/sshd_config.d 不存在，跳过 SSH 恢复"
    fi

    ok "Fail2ban已卸载"
}

show_status(){
    systemctl is-active --quiet fail2ban || { warn "Fail2ban未运行"; return; }
    ok "Fail2ban运行中"
    fail2ban-client status
    echo
    fail2ban-client status sshd || warn "sshd jail 未启用"
    echo
    journalctl -u fail2ban -n 20 --no-pager
}

show_banned(){
    check_fail2ban_running
    fail2ban-client status sshd
    read -p "查看封禁IP? (y/N): " c
    [[ "$c" =~ ^[yY]$ ]] && fail2ban-client get sshd banip
}

ban_ip(){
    check_fail2ban_running
    read -p "IP: " IP
    [ -z "$IP" ] && error "IP不能为空"
    fail2ban-client set sshd banip "$IP"
    ok "已封禁 $IP"
}

unban_ip(){
    check_fail2ban_running
    read -p "IP: " IP
    [ -z "$IP" ] && error "IP不能为空"
    fail2ban-client set sshd unbanip "$IP"
    ok "已解封 $IP"
}

view_log(){
    info "实时日志 Ctrl+C返回"
    set +e
    trap 'echo; ok "已退出日志查看"; trap - INT' INT
    journalctl -u fail2ban -n 100 -f
    trap - INT
    set -e
}

restart_fail2ban(){
    check_installed || error "Fail2ban 未安装"
    systemctl restart fail2ban
    if systemctl is-active --quiet fail2ban; then
        ok "Fail2ban已重启"
    else
        journalctl -u fail2ban -n 50 --no-pager
        error "Fail2ban 重启失败"
    fi
}

menu(){
while true; do
clear
echo "================================="
echo " Fail2ban 管理工具"
echo "================================="
echo "1) 安装 Fail2ban"
echo "2) 卸载 Fail2ban"
echo "3) 查看状态"
echo "4) 查看封禁IP"
echo "5) 封禁IP"
echo "6) 解封IP"
echo "7) 重载配置"
echo "8) 重启Fail2ban"
echo "9) 查看日志"
echo "10)退出"
read -p "选择: " n
case "$n" in
1) install_fail2ban ;;
2) uninstall_fail2ban ;;
3) show_status ;;
4) show_banned ;;
5) ban_ip ;;
6) unban_ip ;;
7) reload_fail2ban ;;
8) restart_fail2ban ;;
9) view_log ;;
10) exit ;;
*) warn "错误选择" ;;
esac
read -p "回车继续..."
done
}

main(){ check_root; menu; }
main
