#!/bin/bash
# ==============================================================================
# Fail2ban Manager (Final Optimized Version)
#
# 支持:
#   Debian 11/12/13
#   Ubuntu 20.04/22.04/24.04
#
# 功能:
#   1. 安装 Fail2ban
#   2. 卸载 Fail2ban
#   3. 查看状态
#
# 场景:
#   公网 VPS
#   SSH 密码登录
# ==============================================================================

set -e
set -o pipefail

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
RESET="\033[0m"

info(){ echo -e "${BLUE}[INFO]${RESET} $1"; }
ok(){ echo -e "${GREEN}[OK]${RESET} $1"; }
warn(){ echo -e "${YELLOW}[WARN]${RESET} $1"; }
error(){ echo -e "${RED}[ERROR]${RESET} $1"; exit 1; }

check_root(){
    [ "$(id -u)" -eq 0 ] || error "请使用 root 权限运行"
}

check_system(){
    [ -f /etc/os-release ] || error "无法识别系统"
    . /etc/os-release

    case "$ID" in
        debian|ubuntu)
            ok "系统: $PRETTY_NAME"
            ;;
        *)
            error "仅支持 Debian / Ubuntu"
            ;;
    esac
}

detect_ssh(){
    command -v sshd >/dev/null || error "未找到 sshd"

    SSH_PORT=$(sshd -T 2>/dev/null | awk '/^port /{print $2}' | head -1)
    [ -z "$SSH_PORT" ] && SSH_PORT=22

    if systemctl list-unit-files | grep -q "^ssh.service"; then
        SSH_SERVICE="ssh"
    elif systemctl list-unit-files | grep -q "^sshd.service"; then
        SSH_SERVICE="sshd"
    else
        SSH_SERVICE="ssh"
    fi
}

detect_firewall(){
    if command -v ufw >/dev/null && ufw status 2>/dev/null | grep -qi "active"; then
        BANACTION="ufw"
    elif systemctl is-active --quiet nftables; then
        BANACTION="nftables-multiport"
    elif command -v iptables >/dev/null; then
        BANACTION="iptables-multiport"
    else
        error "未检测到可用防火墙"
    fi

    ok "Ban Action: ${BANACTION}"
}

detect_ipv6(){
    if [ "$(cat /proc/sys/net/ipv6/conf/all/disable_ipv6 2>/dev/null)" = "1" ] || \
       [ "$(cat /proc/sys/net/ipv6/conf/default/disable_ipv6 2>/dev/null)" = "1" ]; then
        ALLOWIPV6="no"
        IGNOREIP="127.0.0.1/8"
    else
        ALLOWIPV6="yes"
        IGNOREIP="127.0.0.1/8 ::1"
    fi
}

install_packages(){
    info "安装 Fail2ban"
    apt-get update
    apt-get install -y fail2ban python3-systemd
    ok "安装完成"
}

backup_ssh(){
    BACKUP="/etc/ssh/sshd_config.backup.$(date +%F-%H%M%S)"
    cp /etc/ssh/sshd_config "$BACKUP"
    ok "SSH备份: $BACKUP"
}

configure_ssh(){
    mkdir -p /etc/ssh/sshd_config.d

cat > /etc/ssh/sshd_config.d/99-security-hardening.conf <<EOF
# Generated by Fail2ban Manager

MaxAuthTries 3
LoginGraceTime 30
MaxSessions 5
LogLevel INFO
EOF

    sshd -t
    systemctl restart "$SSH_SERVICE"
    ok "SSH限制配置完成"
}

configure_fail2ban(){
    mkdir -p /etc/fail2ban/jail.d

    detect_firewall
    detect_ipv6

cat > /etc/fail2ban/jail.d/sshd-production.local <<EOF
[DEFAULT]
allowipv6 = ${ALLOWIPV6}
backend = systemd
banaction = ${BANACTION}
logtarget = /var/log/fail2ban.log
ignoreip = ${IGNOREIP}
findtime = 10m
bantime = 48h

[sshd]
enabled = true
port = ${SSH_PORT}
mode = aggressive
maxretry = 3

[recidive]
enabled = true
logpath = /var/log/fail2ban.log
findtime = 7d
maxretry = 5
bantime = 30d
EOF

    ok "Fail2ban配置完成"
}

test_fail2ban(){
    info "验证Fail2ban配置..."
    if fail2ban-client -t; then
        ok "配置验证通过"
    else
        error "配置验证失败"
    fi
}

start_fail2ban(){
    systemctl enable fail2ban
    systemctl restart fail2ban
    sleep 3

    if systemctl is-active --quiet fail2ban; then
        ok "Fail2ban运行正常"
    else
        journalctl -u fail2ban -n 50
        error "Fail2ban启动失败"
    fi
}

install_fail2ban(){
    check_system
    detect_ssh

    echo
    echo "=============================="
    echo " Fail2ban 当前配置"
    echo "=============================="
    echo "SSH端口      : ${SSH_PORT}"
    echo "IPv6支持     : ${ALLOWIPV6}"
    echo "Ban Action   : ${BANACTION}"
    echo "Ban Time     : 48h"
    echo "Find Time    : 10m"
    echo "Max Retry    : 3"
    echo "=============================="
    echo

    read -p "确认安装? (y/N): " confirm
    [[ "$confirm" != "y" && "$confirm" != "Y" ]] && exit 0

    install_packages
    backup_ssh
    configure_ssh
    configure_fail2ban
    test_fail2ban
    start_fail2ban

    ok "Fail2ban安装完成"
}

uninstall_fail2ban(){
    echo
    echo "将删除:"
    echo "- Fail2ban软件"
    echo "- Fail2ban配置"
    echo "- Jail配置"
    echo "- Fail2ban日志"
    echo

    read -p "确认卸载? 输入 yes: " confirm
    [ "$confirm" != "yes" ] && exit 0

    info "停止服务"
    systemctl stop fail2ban 2>/dev/null || true
    systemctl disable fail2ban 2>/dev/null || true

    info "卸载软件"
    apt-get remove --purge -y fail2ban || true
    apt-get autoremove -y || true

    info "删除配置"
    rm -rf /etc/fail2ban
    rm -rf /var/log/fail2ban*
    rm -rf /run/fail2ban

    systemctl daemon-reload
    systemctl reset-failed fail2ban 2>/dev/null || true

    ok "Fail2ban已完全卸载"
}

show_status(){
    echo

    if systemctl is-active --quiet fail2ban; then
        ok "Fail2ban运行中"
    else
        warn "Fail2ban未运行"
        return
    fi

    echo
    fail2ban-client status

    echo
    echo "------------------------------"
    echo "SSH Jail"
    echo "------------------------------"
    fail2ban-client status sshd

    echo
    echo "最近封禁记录："
    journalctl -u fail2ban -n 20 --no-pager
}

menu(){
    clear

    echo "================================="
    echo " Fail2ban 管理工具"
    echo "================================="
    echo
    echo "1) 安装 Fail2ban"
    echo "2) 卸载 Fail2ban"
    echo "3) 查看状态"
    echo "4) 退出"
    echo

    read -p "请选择: " choice

    case "$choice" in
        1) install_fail2ban ;;
        2) uninstall_fail2ban ;;
        3) show_status ;;
        4) exit 0 ;;
        *) error "无效选择" ;;
    esac
}

main(){
    check_root
    menu
}

main
