#!/bin/bash

# ==============================================================================
#
# Fail2ban Production Installer
#
# Supported:
#   Debian 11/12/13
#   Ubuntu 20.04/22.04/24.04
#
# Scenario:
#   Public VPS
#   SSH password login
#
# ==============================================================================


set -e
set -o pipefail


# ==========================
# Colors
# ==========================

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
RESET="\033[0m"


info(){
    echo -e "${BLUE}[INFO]${RESET} $1"
}

ok(){
    echo -e "${GREEN}[ OK ]${RESET} $1"
}

warn(){
    echo -e "${YELLOW}[WARN]${RESET} $1"
}

error(){
    echo -e "${RED}[FAIL]${RESET} $1"
    exit 1
}



# ==========================
# Root check
# ==========================

check_root(){

    if [ "$(id -u)" != "0" ]; then
        error "请使用 root 权限运行"
    fi

}



# ==========================
# OS check
# ==========================

check_system(){

    if [ ! -f /etc/os-release ]; then
        error "无法识别系统"
    fi


    . /etc/os-release


    case "$ID" in

        debian|ubuntu)
            ok "检测系统: $PRETTY_NAME"
            ;;

        *)
            error "仅支持 Debian / Ubuntu"
            ;;

    esac

}



# ==========================
# Detect SSH
# ==========================

detect_ssh(){


    if ! command -v sshd >/dev/null; then

        error "未找到 sshd"

    fi



    SSH_PORT=$(sshd -T 2>/dev/null \
    | awk '/^port /{print $2}' \
    | head -1)



    [ -z "$SSH_PORT" ] && SSH_PORT=22



    if systemctl list-unit-files \
    | grep -q "^ssh.service"
    then

        SSH_SERVICE="ssh"

    elif systemctl list-unit-files \
    | grep -q "^sshd.service"
    then

        SSH_SERVICE="sshd"

    else

        SSH_SERVICE="ssh"

    fi



    ok "SSH服务: $SSH_SERVICE"

    ok "SSH端口: $SSH_PORT"


}



# ==========================
# Detect firewall
# ==========================

detect_firewall(){


    if command -v ufw >/dev/null \
    && ufw status 2>/dev/null \
    | grep -q active
    then

        BANACTION="ufw"

        ok "检测防火墙: UFW"


    elif command -v nft >/dev/null
    then

        BANACTION="nftables-multiport"

        ok "检测防火墙: nftables"


    else

        BANACTION="iptables-multiport"

        warn "使用iptables"

    fi


}



# ==========================
# User config
# ==========================

input_config(){


    echo


    read -p \
    "最大失败次数 [默认3]: " MAXRETRY

    MAXRETRY=${MAXRETRY:-3}



    read -p \
    "首次封禁时间(小时) [默认48]: " BANTIME

    BANTIME=${BANTIME:-48}



    CURRENT_IP=$(who am i 2>/dev/null \
    | awk '{print $5}' \
    | tr -d '()')



    if [ -z "$CURRENT_IP" ]; then

        CURRENT_IP=""

    fi



}



# ==========================
# Install packages
# ==========================

install_package(){


    info "更新软件源"


    apt-get update



    apt-get install -y \
        fail2ban \
        python3-systemd \
        nftables



    ok "软件安装完成"


}



# ==========================
# Backup SSH
# ==========================

backup_ssh(){


    BACKUP="/etc/ssh/sshd_config.backup.$(date +%F-%H%M%S)"


    cp /etc/ssh/sshd_config "$BACKUP"


    ok "SSH配置备份: $BACKUP"


}



# ==========================
# SSH hardening
# ==========================

configure_ssh(){


    mkdir -p /etc/ssh/sshd_config.d



cat > /etc/ssh/sshd_config.d/99-security-hardening.conf <<EOF

# Generated by Fail2ban installer

MaxAuthTries 3

LoginGraceTime 30

MaxSessions 5

EOF



    sshd -t



    systemctl restart "$SSH_SERVICE"



    ok "SSH安全参数完成"


}



# ==========================
# Fail2ban config
# ==========================

configure_fail2ban(){


    mkdir -p /etc/fail2ban/jail.d



    IGNORE="127.0.0.1/8 ::1"


    if [ -n "$CURRENT_IP" ]; then

        IGNORE="$IGNORE $CURRENT_IP"

    fi



cat > /etc/fail2ban/jail.d/sshd-production.local <<EOF


[DEFAULT]

backend = systemd

banaction = ${BANACTION}

logtarget = /var/log/fail2ban.log

ignoreip = ${IGNORE}

findtime = 10m

bantime = ${BANTIME}h



[sshd]

enabled = true

port = ${SSH_PORT}

mode = aggressive

maxretry = ${MAXRETRY}



[recidive]

enabled = true

logpath = /var/log/fail2ban.log

findtime = 7d

maxretry = 5

bantime = 30d


EOF



ok "Fail2ban配置完成"


}



# ==========================
# Test
# ==========================

test_config(){


    info "检测 Fail2ban 配置"


    fail2ban-client -t


}



# ==========================
# Start
# ==========================

start_service(){


    systemctl enable fail2ban


    systemctl restart fail2ban



    sleep 3



    if systemctl is-active --quiet fail2ban

    then

        ok "Fail2ban运行正常"

    else

        journalctl -u fail2ban -n 50

        error "Fail2ban启动失败"

    fi


}



# ==========================
# Summary
# ==========================

summary(){


echo

echo "========================================"

echo " Fail2ban部署完成"

echo

echo " SSH端口       : $SSH_PORT"

echo " SSH服务       : $SSH_SERVICE"

echo " 最大失败次数  : $MAXRETRY"

echo " 首次封禁      : ${BANTIME}小时"

echo " 防火墙动作    : $BANACTION"

echo " 二次封禁      : 30天"

echo

echo "查看状态:"

echo "fail2ban-client status sshd"

echo

echo "查看封禁:"

echo "fail2ban-client status recidive"

echo

echo "========================================"


}



# ==========================
# Main
# ==========================

main(){


check_root

check_system

detect_ssh

detect_firewall

input_config



echo

read -p \
"确认安装 Fail2ban? (y/N): " CONFIRM


if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]

then

    exit 0

fi



install_package

backup_ssh

configure_ssh

configure_fail2ban

test_config

start_service

summary


}



main
