#!/bin/bash
# ==============================================================================
# Fail2ban Manager (Final Integrated Production Version)
#
# 支持:
#   Debian 11/12/13
#   Ubuntu 20.04/22.04/24.04
#
# 功能:
#   1. 安装 Fail2ban（含 SSH 加固）
#   2. 卸载 Fail2ban（完整恢复 SSH）
#   3. 查看状态
#   4. 查看封禁IP
#   5. 手动封禁/解封
#   6. 查看实时日志（Ctrl+C 返回菜单）
#   7. 重载配置
#   8. 重启 Fail2ban
#
# 场景:
#   公网 VPS
#   SSH 防爆破
# ==============================================================================

set -e
set -o pipefail

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
RESET="\033[0m"

info(){ echo -e "${BLUE}[INFO]${RESET} $1"; }
ok(){ echo -e "${GREEN}[OK]${RESET} $1"; }
warn(){ echo -e "${YELLOW}[WARN]${RESET} $1"; }
error(){ echo -e "${RED}[ERROR]${RESET} $1"; exit 1; }

check_root(){
    [ "$(id -u)" -eq 0 ] || error "请使用 root 权限运行"
}

check_system(){
    [ -f /etc/os-release ] || error "无法识别系统"
    . /etc/os-release
    case "$ID" in
        debian|ubuntu) ok "系统: $PRETTY_NAME" ;;
        *) error "仅支持 Debian / Ubuntu" ;;
    esac
}

check_installed(){
    dpkg -s fail2ban >/dev/null 2>&1
}

detect_ssh(){
    command -v sshd >/dev/null || error "未找到 sshd"

    SSH_PORT=$(sshd -T 2>/dev/null | awk '/^port /{print $2}' | head -1)
    [ -z "$SSH_PORT" ] && SSH_PORT=22

    if systemctl list-unit-files | grep -q "^ssh.service"; then
        SSH_SERVICE="ssh"
    elif systemctl list-unit-files | grep -q "^sshd.service"; then
        SSH_SERVICE="sshd"
    else
        SSH_SERVICE="ssh"
    fi

    ok "SSH服务: ${SSH_SERVICE}"
    ok "SSH端口: ${SSH_PORT}"
}

detect_firewall(){
    # 不检测 ufw，因为 fail2ban 默认不使用 ufw
    if [ -f /etc/fail2ban/action.d/nftables-multiport.conf ]; then
        BANACTION="nftables-multiport"
        ok "Ban Action: nftables-multiport"
        return
    fi

    if [ -f /etc/fail2ban/action.d/iptables-multiport.conf ]; then
        BANACTION="iptables-multiport"
        ok "Ban Action: iptables-multiport"
        return
    fi

    error "Fail2ban 未找到可用的防火墙 action（nftables / iptables）"
}

install_packages(){
    info "安装 Fail2ban"
    apt-get update
    apt-get install -y fail2ban python3-systemd
    ok "Fail2ban安装完成"
}

backup_ssh(){
    TIMESTAMP=$(date +%F-%H%M%S)

    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$TIMESTAMP

    if [ -d /etc/ssh/sshd_config.d ]; then
        cp -r /etc/ssh/sshd_config.d /etc/ssh/sshd_config.d.backup.$TIMESTAMP
    fi

    ok "SSH配置已完整备份: $TIMESTAMP"
}

restore_ssh(){
    if ls /etc/ssh/sshd_config.backup.* 1>/dev/null 2>&1; then
        LATEST=$(ls -t /etc/ssh/sshd_config.backup.* | head -1)
        cp "$LATEST" /etc/ssh/sshd_config
        ok "已恢复 SSH 主配置: $LATEST"
    fi

    if ls /etc/ssh/sshd_config.d.backup.* 1>/dev/null 2>&1; then
        LATEST_DIR=$(ls -t /etc/ssh/sshd_config.d.backup.* | head -1)
        rm -rf /etc/ssh/sshd_config.d
        cp -r "$LATEST_DIR" /etc/ssh/sshd_config.d
        ok "已恢复 SSH 子配置目录: $LATEST_DIR"
    fi

    if command -v sshd >/dev/null 2>&1; then
        sshd -t && systemctl reload ssh || systemctl reload sshd
        ok "SSH 已重新加载"
    fi
}

configure_journal(){
    mkdir -p /etc/systemd/journald.conf.d
    cat > /etc/systemd/journald.conf.d/99-log-limit.conf <<EOF
[Journal]
SystemMaxUse=300M
SystemMaxFileSize=20M
MaxRetentionSec=30day
Compress=yes
EOF
    systemctl restart systemd-journald
    ok "系统日志限制完成"
}

configure_ssh(){
    mkdir -p /etc/ssh/sshd_config.d
    SSH_HARDEN="/etc/ssh/sshd_config.d/99-security-hardening.conf"

    [ -f "$SSH_HARDEN" ] && cp "$SSH_HARDEN" "${SSH_HARDEN}.backup.$(date +%F-%H%M%S)"

    cat > "$SSH_HARDEN" <<EOF
# Generated by Fail2ban Manager
MaxAuthTries 3
LoginGraceTime 30
MaxSessions 5
LogLevel INFO
EOF

    sshd -t
    systemctl reload "$SSH_SERVICE"
    ok "SSH配置生效"
}

configure_fail2ban(){
    mkdir -p /etc/fail2ban/jail.d
    F2B_CONFIG="/etc/fail2ban/jail.d/sshd-production.local"

    [ -f "$F2B_CONFIG" ] && cp "$F2B_CONFIG" "${F2B_CONFIG}.backup.$(date +%F-%H%M%S)"

    cat > "$F2B_CONFIG" <<EOF
[DEFAULT]
backend = systemd
banaction = ${BANACTION}
logtarget = SYSTEMD-JOURNAL
ignoreip = 127.0.0.1/8 ::1
findtime = 10m
bantime = 48h

[sshd]
enabled = true
port = ${SSH_PORT}
mode = aggressive
maxretry = 3
journalmatch = _SYSTEMD_UNIT=${SSH_SERVICE}.service

[recidive]
enabled = true
backend = systemd
journalmatch = _SYSTEMD_UNIT=fail2ban.service
findtime = 7d
maxretry = 5
bantime = 30d
EOF

    ok "Fail2ban配置完成"
}

test_fail2ban(){
    info "验证Fail2ban配置"
    fail2ban-client -t && ok "配置验证通过" || error "Fail2ban配置错误"
}

start_fail2ban(){
    systemctl enable fail2ban
    systemctl restart fail2ban
    sleep 3
    systemctl is-active --quiet fail2ban || {
        journalctl -u fail2ban -n 50 --no-pager
        error "Fail2ban启动失败"
    }
    ok "Fail2ban运行正常"
}

reload_fail2ban(){
    info "重新加载Fail2ban配置"
    test_fail2ban
    fail2ban-client reload
    ok "Fail2ban配置已重新加载"
}

install_fail2ban(){
    check_system
    detect_ssh
    detect_firewall

    echo
    echo "=============================="
    echo " 即将安装 Fail2ban 并加固 SSH"
    echo "=============================="
    echo "SSH服务    : ${SSH_SERVICE}"
    echo "SSH端口    : ${SSH_PORT}"
    echo "Ban Action : ${BANACTION}"
    echo "Ban Time   : 48h"
    echo "Find Time  : 10m"
    echo "Max Retry  : 3"
    echo "=============================="
    echo

    read -p "确认继续? (y/N): " confirm
    [[ "$confirm" != "y" && "$confirm" != "Y" ]] && exit 0

    ! check_installed && install_packages

    backup_ssh
    configure_journal
    configure_ssh
    configure_fail2ban
    test_fail2ban
    start_fail2ban

    ok "Fail2ban安装并配置完成"
}

uninstall_fail2ban(){
    echo
    echo "=============================="
    echo " 卸载 Fail2ban（含 SSH 完整恢复）"
    echo "=============================="
    echo
    read -p "确认卸载? 输入 yes: " confirm
    [ "$confirm" != "yes" ] && exit 0

    systemctl stop fail2ban || true
    systemctl disable fail2ban || true

    apt-get remove --purge -y fail2ban || true
    apt-get autoremove -y || true

    rm -rf /etc/fail2ban /run/fail2ban /var/log/fail2ban.log

    restore_ssh

    systemctl daemon-reload
    systemctl reset-failed fail2ban || true

    ok "Fail2ban已卸载并恢复 SSH"
}

show_status(){
    echo
    systemctl is-active --quiet fail2ban || { warn "Fail2ban未运行"; return; }

    ok "Fail2ban运行中"
    echo
    fail2ban-client status
    echo "------------------------------"
    echo "SSH Jail"
    echo "------------------------------"
    fail2ban-client status sshd || true
    echo
    journalctl -u fail2ban -n 20 --no-pager
}

show_banned(){
    echo
    info "当前封禁状态"
    fail2ban-client status sshd || true
    echo
    read -p "查看详细封禁IP? (y/N): " confirm
    [[ "$confirm" =~ ^[yY]$ ]] && fail2ban-client get sshd banip
}

check_fail2ban(){
    systemctl is-active --quiet fail2ban || error "Fail2ban未运行"
}

ban_ip(){
    check_fail2ban
    read -p "请输入封禁IP: " IP
    [ -z "$IP" ] && error "IP不能为空"
    fail2ban-client set sshd banip "$IP" && ok "已封禁: $IP" || error "封禁失败"
}

unban_ip(){
    check_fail2ban
    read -p "请输入解封IP: " IP
    [ -z "$IP" ] && error "IP不能为空"
    fail2ban-client set sshd unbanip "$IP" && ok "已解封: $IP" || error "解封失败"
}

view_log(){
    info "实时查看Fail2ban日志 (Ctrl+C 返回菜单)"
    echo

    set +e

    trap 'echo; ok "已退出日志查看"; trap - INT; return' INT

    journalctl -u fail2ban -n 100 -f

    set -e
}

restart_fail2ban(){
    info "重启Fail2ban"
    systemctl restart fail2ban && ok "Fail2ban已重启" || {
        journalctl -u fail2ban -n 50 --no-pager
        error "Fail2ban重启失败"
    }
}

menu(){
    while true; do
        clear
        echo "================================="
        echo " Fail2ban 管理工具"
        echo "================================="
        echo "1) 安装 Fail2ban"
        echo "2) 卸载 Fail2ban（恢复 SSH）"
        echo "3) 查看状态"
        echo "4) 查看封禁IP"
        echo "5) 手动封禁IP"
        echo "6) 解封IP"
        echo "7) 重载配置"
        echo "8) 重启Fail2ban"
        echo "9) 查看实时日志"
        echo "10) 退出"
        echo
        read -p "请选择: " choice
        case "$choice" in
            1) install_fail2ban ;;
            2) uninstall_fail2ban ;;
            3) show_status ;;
            4) show_banned ;;
            5) ban_ip ;;
            6) unban_ip ;;
            7) reload_fail2ban ;;
            8) restart_fail2ban ;;
            9) view_log ;;
            10) exit 0 ;;
            *) warn "无效选择" ;;
        esac
        echo
        read -p "按回车继续..."
    done
}

main(){
    check_root
    menu
}

main
